### ISSUE TITLE
Preview of website in blue

### ISSUE THREAD

**Issue by niklasmh** [AscendNTNU/ascendntnu-web#68]
Dronepage:
![image](https://user-images.githubusercontent.com/8504538/32742730-9931006a-c8aa-11e7-8083-2e98c80280a6.png)

Footer:
![image](https://user-images.githubusercontent.com/8504538/32742680-79d13d0c-c8aa-11e7-98c8-f053e32080ae.png)

Teampage:
![image](https://user-images.githubusercontent.com/8504538/32742869-f6880f2e-c8aa-11e7-972c-af36c7d189e0.png)

**Comment by anders-hopland** [comment]
Not today, Niklas ;)
